POST http://localhost:3001/api/users/signin
content-type: application/json

{
    
    "email": "jane123@gmail.com",
    "password": "1234"
}


###
POST http://localhost:3001/api/users/signup
content-type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane123@gmail.com",
    "password": "1234"
}

###
GET http://localhost:3001/api/users/3

###
POST http://localhost:3001/api/catagories/
content-type: application/json

{
    "catagory_name": "laptops"
}

###
POST http://localhost:3001/api/products
content-type: application/json

{
    "price": 105,
    "productName": "earphone",
    "specification": "Generate Lorem Ipsum placeholder text for use in your graphic, print and web layouts, and discover plugins for your favorite writing, design and blogging tools. Explore the origins, history and meaning of the famous passage, and learn how Lorem Ipsum went from scrambled Latin passage to ubiqitous",
    "quantity": 7,
    "imgPublicId": "electronics-shop/ty6q0jycnhldozlagjfq",
    "imgUrl": "https://res.cloudinary.com/dydwwtmnj/image/upload/v1665660242/electronics-shop/ty6q0jycnhldozlagjfq.jpg",
    "catagoryId": 3
}

###
GET http://localhost:3001/api/products/all

###
GET  http://localhost:3001/api/products/1

###
GET http://localhost:3001/api/catagories

###
POST http://localhost:3001/api/cart/
content-type: application/json,
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJTcGFycm93IiwibGFzdE5hbWUiOiJTaGVycGEiLCJpZCI6MywiaWF0IjoxNjY1OTMyMzIwLCJleHAiOjE2NjU5MzU5MjB9.e7B3zIVmk9G5f7TEw96-OJGBHuihOdnLrX-Xe1Lc4Ko

{
    "quantity": 1,
    "productId": 1,
}

###
GET http://localhost:3001/api/cart

###
GET http://localhost:3001/api/cart/10

###
POST http://localhost:3001/api/orders
content-type: application/json,
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKYW5lIiwibGFzdE5hbWUiOiJEb2UiLCJpZCI6NSwiaWF0IjoxNjY3NzUwNzczLCJleHAiOjE2Njc3NTQzNzN9.8dQ1eCztVH_Hq18Eg-H0cInHn8sRl6xP1k8U0gJEAlY

{
    "quantity": 1,
    "status": "pending",
    "address": "Ktm, Nepal"
}

###
GET http://localhost:3001/api/orders
content-type: application/json,
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKYW5lIiwibGFzdE5hbWUiOiJEb2UiLCJpZCI6NSwiaWF0IjoxNjY3NzUwNzczLCJleHAiOjE2Njc3NTQzNzN9.8dQ1eCztVH_Hq18Eg-H0cInHn8sRl6xP1k8U0gJEAlY

###
GET http://localhost:3001/api/order/2

###
GET http://localhost:3001/api/shipping_address

###
GET http://localhost:3001/api/shipping_address/2